[package]
name = "main"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solver = { path = "../solver" }
rand = "0.8.4"
serde = "1.0.217"
serde_json = "1.0.137"
num_cpus = "1.16.0"
